const DEFAULT_HTTP_TIMEOUT_MS = 12000;
const DEFAULT_CHECKOUT_EXPIRY_MINUTES = 25;

const CONFIG = {
  ENTITY_ID: "8a8294184e736012014e78c4c4cb17dc", // official sandbox entity
  BEARER_TOKEN: "OGE4Mjk0MTg0ZTczNjAxMjAxNGU3OGM0YzRlNDE3ZTB8NHRKQ21qMkJ0Mw==", // sandbox token for registration
  API_BASE: "https://eu-test.oppwa.com",
};

export { DEFAULT_HTTP_TIMEOUT_MS, DEFAULT_CHECKOUT_EXPIRY_MINUTES, CONFIG };
